name: CI/CD - Train and Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  train:
    # This job is exactly the same as before.
    # It acts as our CI check to make sure the code and training works.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python src/train.py

  deploy:
    runs-on: ubuntu-latest
    needs: train # Depends on the 'train' job succeeding
    steps:
      # This step triggers the Render deploy hook
      - name: Trigger Render Deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"